package<%-$.invoke('make-package')%>.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="PLACEHOLDER_<%= metadata.project.name.toUpperCase() %>_<%=entity.name%>.toUpperCase()_TABLE_NAME")public class<%=entity.name%>{

private String id<%=entity.name%>;

<%-$.invokeLoop('property-entity',entity.properties)%>

public<%=entity.name%>(){
// TODO Auto-generated constructor stub
}

@DynamoDBHashKey(attributeName="id<%= entity.name.toLowerCase() %>")@DynamoDBAutoGeneratedKey public String getId<%=entity.name%>(){return this.id<%=entity.name%>;}

ublic void setId<%=entity.name%>(String id<%=entity.name%>){this.id<%=entity.name%>=id<%=entity.name%>;}

<%-$.invokeLoop('property-get-range-key',entity.properties)%><%-$.invokeLoop('property-set-range-key',entity.properties)%>

<%-$.invokeLoop('property-get',entity.properties)%><%-$.invokeLoop('property-set',entity.properties)%>

public String toString(){
// return String.format("Produto [id=%s, name=%s, price=$%f]", this.id,
// this.name, this.price);
